reset;
option solver cplex;

model biofuel.mod;

# data biofuel_transport.dat;
# data biofuel_refinery.dat;
# data biofuel_feedstock.dat;

data biofuel.dat;

solve;

# display variables
display refinery_open;
display feedstock_acquired;
display feedstock_transported;
display ethanol_transported;
display designed_refinery_capacity;
display shortage_ethanol;
display ethanol_production;


# expand constraints
